puppet: suppress deprecation warnings
when running the following command spicerack fails to parse the json
output due to the deprecation warning
  puppet ca --render-as json list --all --subject

  Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/spicerack/puppet.py", line 477, in _run_json_command
    response = json.loads(lines)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
  json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "/usr/lib/python3/dist-packages/spicerack/cookbook.py", line 410, in _run
      ret = self.module.run(args, self.spicerack)
    File "/home/jbond/cookbook/cookbooks/cookbooks/sre/puppet/renew-cert.py", line 51, in run
      puppet_master.wait_for_csr(remote_host_str)
    File "/usr/lib/python3/dist-packages/spicerack/decorators.py", line 96, in wrapper
      return func(*args, **kwargs)  # type: ignore
    File "/usr/lib/python3/dist-packages/spicerack/puppet.py", line 407, in wait_for_csr
      state = self.get_certificate_metadata(hostname)['state']
    File "/usr/lib/python3/dist-packages/spicerack/puppet.py", line 439, in get_certificate_metadata
      pattern=hostname.replace('.', r'\.')))
    File "/usr/lib/python3/dist-packages/spicerack/puppet.py", line 480, in _run_json_command
      command=command, lines=lines)) from e
  spicerack.puppet.PuppetMasterError: Unable to parse Puppet master response for command
    "puppet ca --render-as json list --all --subject "sretest1001\.eqiad\.wmnet"":
    Warning: 'puppet ca' is deprecated and will be removed in a future release
    (location: /usr/lib/ruby/vendor_ruby/puppet/application/face_base.rb:244:in `main')
  [{"name":"sretest1001.eqiad.wmnet","state":"requested",
    "fingerprint":"68:18:BF:08:33:5A:34:1D:A2:2D:04:42:F5:9E:74:A3:91:92:51:1C:5B:D6:59:6A:B1:C0:2A:DD:F3:DE:77:66",
    "fingerprints":{"default": "68:18:BF:08:33:5A:34:1D:A2:2D:04:42:F5:9E:74:A3:91:92:51:1C:5B:D6:59:6A:B1:C0:2A:DD:F3:DE:77:66",
      "SHA1":"73:20:78:21:34:E5:91:62:47:3C:AC:0F:2C:99:FA:74:CD:BA:11:8A",
      "SHA224":"92:09:BC:48:AF:75:D8:70:91:2D:5C:4F:54:1B:F9:16:D3:8E:94:71:2E:6C:FE:16:E4:2D:A9:D7",
      "SHA256":"68:18:BF:08:33:5A:34:1D:A2:2D:04:42:F5:9E:74:A3:91:92:51:1C:5B:D6:59:6A:B1:C0:2A:DD:F3:DE:77:66",
      "SHA384":"C6:D9:02:8B:A0:16:43:81:F6:86:18:FC:F5:0D:D8:E5:F9:C3:EF:02:64:B9:42:68:74:B0:69:BE:3D:90:64:81:
        C7:2C:CF:21:A9:7D:CB:CF:F9:5D:94:3F:2A:84:AD:33",
      "SHA512":"25:01:E6:F0:9C:19:19:AD:D9:89:D8:29:AA:C1:EC:F8:A3:1F:27:08:2A:3F:6E:8C:EB:FC:20:00:A7:16:1F:EF:
        29:2B:47:A6:3D:36:6B:34:6E:87:9F:D4:66:4C:A1:24:A6:28:2E:C5:B9:70:CA:67:56:F5:F2:84:B5:45:0B:65"},
      "dns_alt_names":[]}]
  END (FAIL) - Cookbook sre.puppet.renew-cert (exit_code=99)

This CR suppresses the deprecation warnings on all puppet ca and puppet
cert commands

Change-Id: Id0f8601a8ece47a7ef5170391e9d09fd056f53c0