Add setuptools to sphinx's tox environment
This is required on recent versions of Python:

Traceback (most recent call last):
  File
"/home/elukey/Wikimedia/spicerack/spicerack/tests/sphinx_checker.py",
line 14, in <module>
    from setuptools import find_packages
ModuleNotFoundError: No module named 'setuptools'

Change-Id: I311bf172dbc4af1c6e30cfc4979276944e6e9c85